### ISSUE TITLE
Incorrect use of force-compress

### ISSUE THREAD

**Issue by Jazztache** [Ethorbit/Steam-Deck-With-LUKS-Encryption-Guide#4]
Article: https://github.com/Ethorbit/SteamDeck-SteamOS-Guides/tree/main/Encrypting-With-LUKS#setting-up-mounting--unlocking
SteamOS Version: 3.5.5 (Latest, Updated 18 Nov 23)

Hello!

I was following the tutorial, and noticed that `cat /mnt/lib/overlays/etc/upper/passwd | cut -d ":" -f 1,3` isn't available because /mnt/lib folder does not exist.
I am not sure if you are referring to that folder but on a different partition. This also doesn't make sense, as this is happening on `nvmen0n1p8`, which was my Linux home, and was wiped (dw, I backed it up) for this process.
I am also using nvme0n1p8 for the new unencrypted_home.

I realised that the tutorial wasn't referring to `nvme0n1p8` for that section, but the root file system at `nvme0n1p6`. Can you please make that clearer in this section? It would be a massive help.

Instead of 
`cat /mnt/lib/overlays/etc/upper/passwd | cut -d ":" -f 1,3`
use
```
umount /dev/nvme0n1p8
mount /dev/nvme0n1p6 /mnt
cat /mnt/lib/overlays/etc/upper/passwd | cut -d ":" -f 1,3 > uuid_reminder.txt
umount /dev/nvme0n1p6
mount /dev/nvme0n1p8
```
and then tell the reader to `cat uuid_reminder.txt` if they need to check it. Even better if you can tell them to do it whilst p6 is still mounted.

Any and all help would be appreciated. Thankyou!

**Comment by Jazztache** [comment]
Additional note: for some reason, the entire directory path exists, but the `passwd` file is missing. I remember setting a password whilst I was using my deck unencrypted... but apparently it's not there.

**Comment by Ethorbit** [comment]
That was an oversight as I should've mentioned to them to unmount home and re-mount steamos partition, or for them to check _before_ unmounting 

the step is not really necessary anyway since it's gonna be 1000 unless someone deliberately changes the deck user's UID, in which case that's entirely their fault if ownership commands don't work as expected.

**Comment by Jazztache** [comment]
Oh okay. I might try the 1000 trick and report back to them. I'd probably more clearly outline that 1000 is the (mostly) universal default and it's only modified if a poweruser does something. Thanks for the clarification.

**Comment by Jazztache** [comment]
Using 1000 doesn't help. When I boot up I get a menu with Current B and Previous A as options.
If I do A, I get:
```
BTRFS error (device nvme0n1p8): unrecognised mount option 'force-compress=zstd:16'
BTRFS error (device nvme0n1p8): open_ctree failed
```
Followed by an emergency mode prompt, and another prompt that the root account is locked.

If I do B, I then get a start job that doesn't complete
`A start job is running for /dev/disk/by-partsets/shared/home (0/ 1min 30s)`
Some other jobs like the Jupiter Controller Firmware and the Authorisation Manager are started...
... then it sits on `[  OK  ]  Started Simple Desktop Display Manager.`
Followed by a completely blank screen with only an underscore after the 1minute and 30 seconds are up.

**Comment by Ethorbit** [comment]
> Using 1000 doesn't help. When I boot up I get a menu with Current B and Previous A as options. If I do A, I get:
> 
> ```
> BTRFS error (device nvme0n1p8): unrecognised mount option 'force-compress=zstd:16'
> BTRFS error (device nvme0n1p8): open_ctree failed
> ```
> 
> Followed by an emergency mode prompt, and another prompt that the root account is locked.
> 
> If I do B, I then get a start job that doesn't complete `A start job is running for /dev/disk/by-partsets/shared/home (0/ 1min 30s)` Some other jobs like the Jupiter Controller Firmware and the Authorisation Manager are started... ... then it sits on `[ OK ] Started Simple Desktop Display Manager.` Followed by a completely blank screen with only an underscore after the 1minute and 30 seconds are up.

The mount option should be **compress-force** not force-compress. The mount fails due to this which is why it's not booting properly.

**Comment by Jazztache** [comment]
Ah alright. I ended up re-imaging my Steam Deck, but I am going to retry the process next week.
Sorry about that I really wanted to jump on Garry's Mod to do some addon testing for someone.
I'll definitely have to give it another try after hearing that. Sorry about that.

**Comment by Jazztache** [comment]
I found the issue. Part of the tutorial uses force-compress and not compress-force.
![image](https://github.com/Ethorbit/SteamDeck-SteamOS-Guides/assets/97380337/ee75bad4-f9d4-407c-bbbf-08ce2b18a659)

**Comment by Ethorbit** [comment]
Thanks, both mistakes should be corrected now. :+1:

**Comment by Jazztache** [comment]
Thanks!
