### ISSUE TITLE
Add a warning that dd is not a secure method of erasing data on ssds

### ISSUE THREAD

**Issue by feliscatusmeows** [Ethorbit/Steam-Deck-With-LUKS-Encryption-Guide#6]
Overwriting an ssd wastes its limited write cycles and has a limited effect due to data duplication and wear leveling. Even the gutman method doesn't result in 100% data deletion. Data can still be recovered directly from the flash chips. Don't quote me but I think this only potentially protects against stuff like photorec and testdisk. 

True secure deletion can be achieved using `nvme-cli format` which all partitions on the nvme. I am unsure of how to securely erase an SD card. 

https://cseweb.ucsd.edu/~swanson/papers/Fast2011SecErase.pdf
https://cseweb.ucsd.edu/~m3wei/assets/pdf/FMS-2010-Secure-Erase.pdf

**Comment by Ethorbit** [comment]
We are using dd on an **encrypted device**, which means every zero is encrypted and no one can know what or where data is stored as it will appear to be completely filled with data.

As for wearing out the SSD by wasting limited write cycles, I do not think this is something to be concerned about unless you were to zero out the disk on a frequent basis, but I think a warning is a good idea as this dd operation is not really necessary, as the data written is encrypted regardless if the device was zero'd out or not.

[Warning added](https://github.com/Ethorbit/SteamDeck-SteamOS-Guides/commit/bcba8383283df268f3c80b308b6d06c5ad8bbb20) thanks.

**Comment by feliscatusmeows** [comment]
Correct me if I'm wrong, but writing encrypted zeros is similar to a single pass random overwrite of the partition, which is ineffective at deleting any data that existed on the steamdeck before doing any repartitioning and encryption setup. See section 5.19 of the luks cryptsetup FAQ. 

The second PDF I linked has a helpful graph on page 18 which I believe shows the effectiveness of various erasure methods on a 1 GB block of data on an ssd. A single pass of pusedorandom data resulted in a data recovery of between 6.16% up to 75.7%. 

This may cause some old data from before the encryption was setup to be leaked, which may be dumped by bypassing the ssd controller and accessing the memory cells directly. 

An attacker could, for example, take the dump and grep for stuff like `@gmail.com` stored in an exported-passwords.CSV file that existed before any of these instructions were followed the user was aware that the steamdeck was unencrypted. 

The odds of this attack is low, and the odds that any single file survives a single-pass overwrite of most of the ssd is even lower, but anyone paranoid enough to attempt to encrypt their drive would want to know that, unless they use the nvme snatize or nvme format command (and trust the drive vendor to implement the command correctly), any data on the steam deck before encryption could potentially be retrieved using a microcontroller that "cost as little as $200, and would require only a moderate amount of technical skill to construct." It is financially plausable for this attack to be done by crime rings purchasing used ssds. 

https://gitlab.com/cryptsetup/cryptsetup/-/wikis/FrequentlyAskedQuestions
